parameters:
#    kunstmaan_k_page_part.example.class: Kunstmaan\PagePartBundle\Example
    kunstmaan_pagepart.form.type.header_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\HeaderPagePartAdminType'
    kunstmaan_pagepart.form.type.line_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\LinePagePartAdminType'
    kunstmaan_pagepart.form.type.link_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\LinkPagePartAdminType'
    kunstmaan_pagepart.form.type.raw_html_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\RawHTMLPagePartAdminType'
    kunstmaan_pagepart.form.type.text_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\TextPagePartAdminType'
    kunstmaan_pagepart.form.type.toc_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\TocPagePartAdminType'
    kunstmaan_pagepart.form.type.to_top_pagepart_admin.class: 'Kunstmaan\PagePartBundle\Form\ToTopPagePartAdminType'

services:
#    kunstmaan_k_page_part.example:
#        class: %kunstmaan_k_page_part.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kunstmaan_pagepart.pageparts:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\Builder

    kunstmaan_pagepartadmin.factory:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory
        arguments: ['@service_container']

    kunstmaan_pagepartadmin.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartAdminTwigExtension
        tags:
            -  { name: twig.extension }

    kunstmaan_pageparts.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartTwigExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
            
    kunstmaan_pagetemplate.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PageTemplateTwigExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@kernel"
        tags:
            - { name: twig.extension }

    kunstmaan_pageparts.pagepart_creator_service:
            class: Kunstmaan\PagePartBundle\Helper\Services\PagePartCreatorService
            calls:
                - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]

    kunstmaan_pageparts.edit_node.listener:
        class: Kunstmaan\PagePartBundle\EventListener\NodeListener
        arguments: ["@doctrine.orm.entity_manager", "@kernel", "@form.factory", "@kunstmaan_pagepartadmin.factory"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

    kunstmaan_pageparts.clone.listener:
        class: Kunstmaan\PagePartBundle\EventListener\CloneListener
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.postDeepCloneAndSave, method: postDeepCloneAndSave }

    form.type.kunstmaan_pagepartbundle_headerpageparttype:
        class: "%kunstmaan_pagepart.form.type.header_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_headerpageparttype }

    form.type.kunstmaan_pagepartbundle_linepageparttype:
        class: "%kunstmaan_pagepart.form.type.line_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_linepageparttype }

    form.type.kunstmaan_pagepartbundle_linkpageparttype:
        class: "%kunstmaan_pagepart.form.type.link_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_linkpageparttype }

    form.type.kunstmaan_pagepartbundle_rawhtmlpageparttype:
        class: "%kunstmaan_pagepart.form.type.raw_html_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_rawhtmlpageparttype }

    form.type.kunstmaan_pagepartbundle_textpageparttype:
        class: "%kunstmaan_pagepart.form.type.text_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_textpageparttype }

    form.type.kunstmaan_pagepartbundle_tocpageparttype:
        class: "%kunstmaan_pagepart.form.type.toc_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_tocpageparttype }

    form.type.kunstmaan_pagepartbundle_totoppageparttype:
        class: "%kunstmaan_pagepart.form.type.to_top_pagepart_admin.class%"
        tags:
            - { name: form.type, alias: kunstmaan_pagepartbundle_totoppageparttype }
