parameters:
    kunstmaan_redirect.menu.adaptor.class: 'Kunstmaan\RedirectBundle\Helper\Menu\RedirectMenuAdaptor'
    kunstmaan_redirect.redirect_repository.class: 'Kunstmaan\RedirectBundle\Repository\RedirectRepository'
    kunstmaan_redirect.redirect.class: 'Kunstmaan\RedirectBundle\Entity\Redirect'
    kunstmaan_redirect.form.type.redirect_admin.class: 'Kunstmaan\RedirectBundle\Form\RedirectAdminType'

services:
    kunstmaan_redirect.menu.adaptor:
        class: "%kunstmaan_redirect.menu.adaptor.class%"
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    kunstmaan_redirect.repositories.redirect:
        class:            "%kunstmaan_redirect.redirect_repository.class%"
        factory_service:  "doctrine.orm.entity_manager"
        factory_method:   getRepository
        arguments:        ["%kunstmaan_redirect.redirect.class%"]

    kunstmaan_redirect.redirectrouter:
        class: Kunstmaan\RedirectBundle\Router\RedirectRouter
        arguments: ["@kunstmaan_redirect.repositories.redirect"]
        tags:
            - { name: router, priority: 1 }

    form.type.redirect_form:
        class: "%kunstmaan_redirect.form.type.redirect_admin.class%"
        tags:
            - { name: form.type, alias: redirect_form }