parameters:
    kunstmaan_media.media_manager.class: 'Kunstmaan\MediaBundle\Helper\MediaManager'
    kunstmaan_media.folder_manager.class: 'Kunstmaan\MediaBundle\Helper\FolderManager'
    kunstmaan_media.menu.adaptor.class: 'Kunstmaan\MediaBundle\Helper\Menu\MediaMenuAdaptor'
    kunstmaan_media.listener.doctrine.class: 'Kunstmaan\MediaBundle\EventListener\DoctrineMediaListener'
    kunstmaan_media.form.type.media.class: 'Kunstmaan\MediaBundle\Form\Type\MediaType'
    kunstmaan_media.form.type.iconfont.class: 'Kunstmaan\MediaBundle\Form\Type\IconFontType'
    kunstmaan_media.icon_font_manager.class: 'Kunstmaan\MediaBundle\Helper\IconFont\IconFontManager'
    kunstmaan_media.icon_font.default_loader.class: 'Kunstmaan\MediaBundle\Helper\IconFont\DefaultIconFontLoader'
    kunstmaan_media.media_creator_service.class: 'Kunstmaan\MediaBundle\Helper\Services\MediaCreatorService'
    kunstmaan_media.mimetype_guesser.factory.class: 'Kunstmaan\MediaBundle\Helper\MimeTypeGuesserFactory'
    kunstmaan_media.form.type.file.class: 'Kunstmaan\MediaBundle\Form\File\FileType'
    kunstmaan_media.form.type.remote_audio.class: 'Kunstmaan\MediaBundle\Form\RemoteAudio\RemoteAudioType'
    kunstmaan_media.form.type.remote_slide.class: 'Kunstmaan\MediaBundle\Form\RemoteSlide\RemoteSlideType'
    kunstmaan_media.form.type.remote_video.class: 'Kunstmaan\MediaBundle\Form\RemoteVideo\RemoteVideoType'
    kunstmaan_media.form.type.bulk_upload.class: 'Kunstmaan\MediaBundle\Form\BulkUploadType'
    kunstmaan_media.form.type.folder.class: 'Kunstmaan\MediaBundle\Form\FolderType'

services:
    liip_imagine.data.loader.stream.profile_photos:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - ''
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'kunstmaan_media_thumbloader' }

    kunstmaan_media.media_manager:
        class: "%kunstmaan_media.media_manager.class%"
        calls:
            - [ setDefaultHandler, [ "@kunstmaan_media.media_handlers.file" ] ]

    kunstmaan_media.listener.doctrine:
        class: "%kunstmaan_media.listener.doctrine.class%"
        arguments: ["@kunstmaan_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }

    form.type.media:
        class: "%kunstmaan_media.form.type.media.class%"
        arguments:
            - "@kunstmaan_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: media }

    form.type.iconfont:
        class: "%kunstmaan_media.form.type.iconfont.class%"
        arguments: ["@kunstmaan_media.icon_font_manager"]
        tags:
            - { name: form.type, alias: iconfont }


    kunstmaan_media.icon_font_manager:
        class: "%kunstmaan_media.icon_font_manager.class%"
        calls:
            - [ setDefaultLoader, [ "@kunstmaan_media.icon_font.default_loader" ] ]

    kunstmaan_media.icon_font.default_loader:
        class: "%kunstmaan_media.icon_font.default_loader.class%"
        arguments: ["@kernel"]
        tags:
            -  { name: 'kunstmaan_media.icon_font.loader' }

    kunstmaan_media.media_creator_service:
        class: "%kunstmaan_media.media_creator_service.class%"
        arguments: ["@service_container"]

    kunstmaan_media.repository.folder:
        class:            Kunstmaan\MediaBundle\Repository\FolderRepository
        factory_service:  "doctrine.orm.entity_manager"
        factory_method:   getRepository
        arguments:        ["KunstmaanMediaBundle:Folder"]

    kunstmaan_media.menu.adaptor:
        class: "%kunstmaan_media.menu.adaptor.class%"
        arguments: ["@kunstmaan_media.repository.folder"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    kunstmaan_media.folder_manager:
        class: "%kunstmaan_media.folder_manager.class%"
        arguments: ["@kunstmaan_media.repository.folder"]

    kunstmaan_media.mimetype_guesser.factory:
        class: "%kunstmaan_media.mimetype_guesser.factory.class%"

    kunstmaan_media.command.migratename:
        class: Kunstmaan\MediaBundle\Command\MigrateNameCommand
        calls:
            - [setContainer, ["@service_container"] ]

    kunstmaan_media.command.rebuildfoldertree:
        class: Kunstmaan\MediaBundle\Command\RebuildFolderTreeCommand
        calls:
            - [setContainer, ["@service_container"] ]

    form.type.kunstmaan_mediabundle_filetype:
        class: "%kunstmaan_media.form.type.file.class%"
        tags:
            - { name: form.type, alias: kunstmaan_mediabundle_filetype }

    form.type.kunstmaan_mediabundle_audiotype:
        class: "%kunstmaan_media.form.type.remote_audio.class%"
        tags:
            - { name: form.type, alias: kunstmaan_mediabundle_audiotype }

    form.type.kunstmaan_mediabundle_slidetype:
        class: "%kunstmaan_media.form.type.remote_slide.class%"
        tags:
            - { name: form.type, alias: kunstmaan_mediabundle_slidetype }

    form.type.kunstmaan_mediabundle_videotype:
        class: "%kunstmaan_media.form.type.remote_video.class%"
        tags:
            - { name: form.type, alias: kunstmaan_mediabundle_videotype }

    form.type.kunstmaan_mediabundle_bulkupload:
        class: "%kunstmaan_media.form.type.bulk_upload.class%"
        tags:
            - { name: form.type, alias: kunstmaan_mediabundle_bulkupload }

    form.type.kunstmaan_mediabundle_FolderType:
        class: "%kunstmaan_media.form.type.file.class%"
        tags:
            -  { name: form.type, alias: kunstmaan_mediabundle_FolderType }